version: "3"

services:

  aggregator_db:
    image: 'postgres:10.2-alpine'
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - TZ=GMT-3
    volumes:
      - ./runtime/aggregator/db:/var/lib/postgresql/data

  offer_db:
    image: 'postgres:10.2-alpine'
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - TZ=GMT-3
    volumes:
      - ./runtime/offer/db:/var/lib/postgresql/data

  page_api_db:
    image: 'postgres:10.2-alpine'
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - TZ=GMT-3
    volumes:
      - ./runtime/page_api/db:/var/lib/postgresql/data

  payment_repository:
    build:
      context: .
      dockerfile: payment_repository/Dockerfile
    volumes:
      - "~/.ssh:~/root/.ssh"
    expose:
      - ${PAYMENT_REPOSITORY_GRPC_PORT}
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${PAYMENT_REPOSITORY_POSTGRES_USER}
      - POSTGRES_PASSWORD=${PAYMENT_REPOSITORY_POSTGRES_PASSWORD}
      - POSTGRES_DB_NAME=${PAYMENT_REPOSITORY_POSTGRES_DB}
      - POSTGRES_SSL_MODE=disable
      - SENTRY_DSN=${PAYMENT_REPOSITORY_SENTRY_DSN}
      - GRPC_PORT=${PAYMENT_REPOSITORY_GRPC_PORT}
    links:
      - payment_db:db

  payment_db:
    image: 'postgres:10.2-alpine'
    environment:
      - POSTGRES_DB=${PAYMENT_REPOSITORY_POSTGRES_DB}
      - POSTGRES_USER=${PAYMENT_REPOSITORY_POSTGRES_USER}
      - POSTGRES_PASSWORD=${PAYMENT_REPOSITORY_POSTGRES_PASSWORD}
      - TZ=GMT-3
    volumes:
      - ./runtime/payment/db:/var/lib/postgresql/data
    expose:
      - 5432

  user_db:
    image: 'postgres:10.2-alpine'
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - TZ=GMT-3
    volumes:
      - ./runtime/user/db:/var/lib/postgresql/data

  order_db:
    image: 'postgres:10.2-alpine'
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - TZ=GMT-3
    volumes:
      - ./runtime/order/db:/var/lib/postgresql/data

  template_db:
    image: 'postgres:10.2-alpine'
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - TZ=GMT-3
    volumes:
      - ./runtime/template/db:/var/lib/postgresql/data

  postback_db:
    image: 'postgres:10.2-alpine'
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - TZ=GMT-3
    volumes:
      - ./runtime/postback/db:/var/lib/postgresql/data


