version: "3"

services:

  stat_repository:
    build:
      context: .
      dockerfile: stat_repository/Dockerfile
    expose:
      - ${STAT_REPOSITORY_GRPC_PORT}
    environment:
      - CLICKHOUSE1_HOST=stat_repository-showcase-clickhouse
      - CLICKHOUSE1_PORT=9011
      - CLICKHOUSE1_USER=default
      - CLICKHOUSE1_PASSWORD=
      - SENTRY_DSN=${SENTRY_DSN}
      - GRPC_PORT=${STAT_REPOSITORY_GRPC_PORT}

  stat_repository-showcase-clickhouse-zookeeper:
    container_name: stat_repository-showcase-clickhouse-zookeeper
    image: zookeeper:3.4.13
    ports:
      - 2181:2181

  stat_repository-showcase-clickhouse:
    container_name: stat_repository-showcase-clickhouse
    image: yandex/clickhouse-server:18.14.19
    ports:
      - 8811:8123
      - 9011:9000
    volumes:
      - ./stat_repository/clickhouse/config/ch1.xml:/etc/clickhouse-server/config.xml
      - ./stat_repository/clickhouse/config/cluster.xml:/etc/clickhouse-server/cluster.xml
      - ./stat_repository/clickhouse/data/ch1:/var/lib/clickhouse
      - ./stat_repository/clickhouse/logs/ch1:/var/log/clickhouse-server

  stat_repository-showcase-clickhouse-2:
    container_name: stat_repository-showcase-clickhouse-2
    image: yandex/clickhouse-server:18.14.19
    ports:
      - 8812:8123
      - 9012:9000
    volumes:
      - ./stat_repository/clickhouse/config/ch2.xml:/etc/clickhouse-server/config.xml
      - ./stat_repository/clickhouse/config/cluster.xml:/etc/clickhouse-server/cluster.xml
      - ./stat_repository/clickhouse/data/ch2:/var/lib/clickhouse
      - ./stat_repository/clickhouse/logs/ch2:/var/log/clickhouse-server

  stat_repository-showcase-clickhouse-3:
    container_name: stat_repository-showcase-clickhouse-3
    image: yandex/clickhouse-server:18.14.19
    ports:
      - 8813:8123
      - 9013:9000
    volumes:
      - ./stat_repository/clickhouse/config/ch3.xml:/etc/clickhouse-server/config.xml
      - ./stat_repository/clickhouse/config/cluster.xml:/etc/clickhouse-server/cluster.xml
      - ./stat_repository/clickhouse/data/ch3:/var/lib/clickhouse
      - ./stat_repository/clickhouse/logs/ch3:/var/log/clickhouse-server

  aggregator_db:
    image: 'postgres:10.2-alpine'
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - TZ=UTC
    volumes:
      - ./runtime/aggregator/db:/var/lib/postgresql/data

  offer_db:
    image: 'postgres:10.2-alpine'
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - TZ=UTC
    volumes:
      - ./runtime/offer/db:/var/lib/postgresql/data

  page_api_db:
    image: 'postgres:10.2-alpine'
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - TZ=UTC
    volumes:
      - ./runtime/page_api/db:/var/lib/postgresql/data

  payment_repository:
    build:
      context: .
      dockerfile: payment_repository/Dockerfile
    expose:
      - ${PAYMENT_REPOSITORY_GRPC_PORT}
    environment:
      - POSTGRES_HOST=payment_db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${PAYMENT_REPOSITORY_POSTGRES_USER}
      - POSTGRES_PASSWORD=${PAYMENT_REPOSITORY_POSTGRES_PASSWORD}
      - POSTGRES_DB_NAME=${PAYMENT_REPOSITORY_POSTGRES_DB}
      - POSTGRES_SSL_MODE=disable
      - SENTRY_DSN=${SENTRY_DSN}
      - GRPC_PORT=${PAYMENT_REPOSITORY_GRPC_PORT}

  payment_db:
    image: 'postgres:10.2-alpine'
    environment:
      - POSTGRES_DB=${PAYMENT_REPOSITORY_POSTGRES_DB}
      - POSTGRES_USER=${PAYMENT_REPOSITORY_POSTGRES_USER}
      - POSTGRES_PASSWORD=${PAYMENT_REPOSITORY_POSTGRES_PASSWORD}
      - TZ=UTC
    volumes:
      - ./runtime/payment/db:/var/lib/postgresql/data
    expose:
      - 5432

  user_db:
    image: 'postgres:10.2-alpine'
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - TZ=UTC
    volumes:
      - ./runtime/user/db:/var/lib/postgresql/data

  order_db:
    image: 'postgres:10.2-alpine'
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - TZ=UTC
    volumes:
      - ./runtime/order/db:/var/lib/postgresql/data

  template_db:
    image: 'postgres:10.2-alpine'
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - TZ=UTC
    volumes:
      - ./runtime/template/db:/var/lib/postgresql/data

  postback_db:
    image: 'postgres:10.2-alpine'
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - TZ=UTC
    volumes:
      - ./runtime/postback/db:/var/lib/postgresql/data


